In [2]:
'''
1. Write a function so that the columns of the output matrix are powers of the input vector. 

'''

##Solution:
import numpy as np
def vander_matrix(input_vector,N,increasing=False):
    desc_order = np.column_stack([input_vector**(N-1-i) for i in range(N)])
    print('Matrix is : \n', desc_order)
x = np.array([1,2,3,5])
num_col = 3
vander_matrix(x,num_col)

Matrix is : 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]


In [4]:
'''
2. Write a function to find moving average in an array over a window:
   Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
'''

## Solution

def moving_average(a, n=1) :
    res = np.cumsum(a, dtype=float)
    res[n:] = res[n:] - res[:-n]
    return res[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
